---
title: "Abstract Plots"
author: "Audrey Mitchell"
date: "7/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(NMF)
library(MutationalPatterns)
library(tidyverse)
library(ggrepel)
library(ROCR)
source("bayes_function.R")
source("get_classification_df.R")
source("simulation.R")
```

```{r}
vector_to_matrix <- function(mutations.vector){
  tab <- table(mutations.vector)/sum(table(mutations.vector))
  #transform table to a data frame and assign column names to mutations and frequencies
  mutations.df <- data.frame(tab)
  colnames(mutations.df) <- c("mutations", "frequencies")
  
  #defines a function that joins two data frames and replaces NA with 0
  left_join_NA <- function(x, y, by) {
    left_join(x = x, y = y, by = by) %>% 
      mutate_each(funs(replace(., which(is.na(.)), 0)))
  }
  
  #converts vector of 96 mutation types to a data frame
  mutation.types.df <- data.frame(mutations)
  #joins together sample probabilities with data frame of mutation types so that all 96 mutation types are included
  complete.mutations.df <- left_join_NA(mutation.types.df, mutations.df, by = "mutations")
  
  #converts data frame of mutation types and frequencies to a data frame and assigns rownames
  mutations.matrix <- as.matrix(complete.mutations.df$frequencies)
  rownames(mutations.matrix) = mutations
  
  return(mutations.matrix)
}
```


```{r}
#load FFPE signature as a matrix
ffpe.signature <- as.matrix(load_old_mutational_matrix("supplied_results/ffpe.signature.txt"))

#create vector of the 96 mutation types
mutations <- rownames(ffpe.signature) 

#Load COSMIC signatures (version 3)
cosmic.signatures <- get_known_signatures(muttype = "snv")

#Create vector of the signature names
signature.names <- colnames(cosmic.signatures)

#Create list of signature matrices with assigned rownames
signature.matrix.list <- list()
for (i in 1:60){
  sig <- cosmic.signatures[,i]
  sig.mat <- as.matrix(sig)
  rownames(sig.mat) <- mutations
  colnames(sig.mat) <- signature.names[i]
  signature.matrix.list[[i]] <- sig.mat
}

#create vector of cosine similarities to the FFPE signature
ffpe.cosmic.cos.sims <- c()
for (i in 1:60){
  cos.sim <- cos_sim_matrix(signature.matrix.list[[i]], ffpe.signature)
  ffpe.cosmic.cos.sims[i] <- cos.sim[1,1]
}

signature.4.mat <- as.matrix(cosmic.signatures[,"SBS4"])
rownames(signature.4.mat) <- mutations

signature.6.mat <- as.matrix(cosmic.signatures[,"SBS6"])
rownames(signature.6.mat) <- mutations
```

#Diagram of Methods

```{r}
mmr.sample <- create_signature_sample_vector(signature.6.mat, 200)
tobacco.sample <- create_signature_sample_vector(signature.4.mat, 200)
ffpe.sample <- create_signature_sample_vector(ffpe.signature, 100)

ex.ffpe.profile.mat <- vector_to_matrix(c(mmr.sample, tobacco.sample, ffpe.sample))
rownames(ex.ffpe.profile.mat) <- mutations

plot_96_profile(ex.ffpe.profile.mat)+
  labs(title = "Mutational Profile")
```

```{r}
sig.mat <- cbind(signature.4.mat, signature.6.mat, ffpe.signature)
colnames(sig.mat) <- c("Signature 4", "Signature 6", "FFPE")
fts.res <- fit_to_signatures(ex.ffpe.profile.mat, sig.mat)

plot_contribution(fts.res$contribution, sig.mat, coord_flip = TRUE)+
  labs(title = "Relative Contributions of Signatures")+
  theme(aspect.ratio = 0.3)
```

```{r}
plot_96_profile(sig.mat)+
  labs(title = "Mutational Signatures")
```

#Diagram of Simulating Data
```{r}
plot_96_profile(signature.4.mat)+
  labs(title = "Signature 4")
```

```{r}
plot_96_profile(ffpe.signature)+
  labs(title = "FFPE Signature")
```

```{r}
sample.4 <- create_signature_sample_vector(signature.4.mat, 100)
sample.ffpe <- create_signature_sample_vector(ffpe.signature, 100)

ex.sim.sample.vec <- c(sample.4, sample.ffpe)
ex.sim.sample <- vector_to_matrix(ex.sim.sample.vec)
plot_96_profile(ex.sim.sample)+
  labs(title = "Simulated Sample Profile")
```


#Scatterplot of Average AUC vs. Cosine Similarity to FFPE
```{r}
#outer for loop: loop through each COSMIC v3 signature
average.auc.values <- c()
for (x in 1:60){
  signature.auc.vec <- c()
  #inner for loop: calculate misclassification rate 10x for each signature
  for (y in 1:10){
    #create a sample vector of 100 mutations for the COSMIC signature corresponding to number x
    sample.vec <- create_signature_sample_vector(signature.matrix.list[[x]],100)
    #Create FFPE sample vector of 100 mutations
    ffpe.sample.vec <- create_signature_sample_vector(ffpe.signature, 100)
    classification.df.1 <- get_classification_df(list(sample.vec, ffpe.sample.vec), c(signature.names[x],"FFPE"), list(signature.matrix.list[[x]], ffpe.signature))
    class.df.colnames <- colnames(classification.df.1)
    sig.name <- class.df.colnames[3]
    classification.df.2 <- classification.df.1 %>%
      mutate(signature.indicator = ifelse(truth == sig.name, 1, 0))
    predictions <- classification.df.2[3]
    labels <- classification.df.2$signature.indicator
    pred <- prediction(predictions, labels)
    auc.perf <- performance(pred, measure = "auc")
    signature.auc.vec[y] <- auc.perf@y.values[[1]][1]
  }
  average.signature.auc <- mean(signature.auc.vec)
  average.auc.values[x] <- average.signature.auc
}
```

```{r}
cos.sim.auc.data <- data.frame(signature.names, ffpe.cosmic.cos.sims, average.auc.values)
colnames(cos.sim.auc.data) <- c("signature", "cosine_similarity", "average_auc")
```

```{r}
model2 <- lm(average_auc ~ cosine_similarity, data = cos.sim.auc.data)

#summary(model2)

model2_summary <- summary(model2)

cos.sim.auc.data$residuals <- model2_summary$residuals

cos.sim.auc.outliers <- cos.sim.auc.data %>%
  filter(residuals >= quantile(cos.sim.auc.data$residuals, 0.95) | 
         residuals <= quantile(cos.sim.auc.data$residuals, 0.05))
```

```{r}
ggplot(cos.sim.auc.data, aes(x = cosine_similarity, y = average_auc))+
  geom_point()+
  geom_smooth(method = "lm")+
  labs(title = "Average area under curve vs. cosine similarity to FFPE", x = "Cosine similarity of COSMIC signature to FFPE signature", y = "Average area under curve (10 iterations)")+
  geom_point(data = cos.sim.auc.outliers, color = "red")+
  geom_label_repel(data = cos.sim.auc.outliers, aes(label = signature), max.overlaps = 10, label.size =   0.1)
  
```

#Scatterplot of Average Sensitivity and Specificity vs. Cosine Similarity to FFPE

```{r}
#outer for loop: loop through each COSMIC v3 signature
average.sensitivity.values <- c()
average.specificity.values <- c()
for (x in 1:60){
  signature.sensitivity.vec <- c()
  signature.specificity.vec <- c()
  #inner for loop: calculate misclassification rate 10x for each signature
  for (y in 1:10){
    #create a sample vector of 100 mutations for the COSMIC signature corresponding to number x
    sample.vec <- create_signature_sample_vector(signature.matrix.list[[x]],100)
    #Create FFPE sample vector of 100 mutations
    ffpe.sample.vec <- create_signature_sample_vector(ffpe.signature, 100)
    classification.df <- get_classification_df(list(sample.vec, ffpe.sample.vec), c(signature.names[x],"FFPE"), list(signature.matrix.list[[x]], ffpe.signature))
    class.df.colnames <- colnames(classification.df)
    sig.name <- class.df.colnames[3]
    #Count number of true positives (for sensititivity)
    sensitivity.df <- classification.df %>%
      filter(truth == sig.name & classify == sig.name)
    #Calculate sensitivity
    sensitivity.val = nrow(sensitivity.df)/100
    #Add to the vector of 10 sensitivity values
    signature.sensitivity.vec[y] = sensitivity.val
    #Count number of true negatives (for specificity)
    specificity.df <- classification.df %>%
      filter(truth == "FFPE" & classify == "FFPE")
    #Calculate specificity
    specificity.val = nrow(specificity.df)/100
    #Add to the vector of 10 specificity values
    signature.specificity.vec[y] = specificity.val
  }
  average.signature.sensitivity <- mean(signature.sensitivity.vec)
  average.sensitivity.values[x] <- average.signature.sensitivity
  average.signature.specificity <- mean(signature.specificity.vec)
  average.specificity.values[x] <- average.signature.specificity
}
```

```{r}
sens.spec.data <- data.frame(signature.names, ffpe.cosmic.cos.sims, average.sensitivity.values, average.specificity.values)

colnames(sens.spec.data) <- c("signature", "cosine_similarity", "sensitivity", "specificity")

sens.spec.data.2 <- sens.spec.data %>%
  pivot_longer(c(sensitivity, specificity), names_to = "measure", values_to = "value")
```

```{r}
ggplot(data = sens.spec.data.2, aes(x = cosine_similarity, y = value, color = measure))+
  geom_point()+
  geom_smooth(method = lm, se = FALSE)+
  labs(title = "Sensitivity & Specificity vs. Cosine Similarity to FFPE Signature", x = "Cosine Similarity of COSMIC Signature to FFPE", y = "Average Sensitivity and Specificity (10 iterations)")
```

