---
title: "Mayo Data Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(NMF)
library(MutationalPatterns)
library(tidyverse)
library(ggrepel)
library(ROCR)
library(gridExtra)
library(mosaic)
library(readr)
source("bayes_function.R")
source("get_classification_df.R")
source("simulation.R")
sessionInfo()
```


```{r}
#load Mayo data
mayo.samples <- read.csv("sample.final.csv")
#load FFPE signature as a matrix
ffpe.signature <- as.matrix(load_old_mutational_matrix("supplied_results/ffpe.signature.txt"))
mutations <- rownames(ffpe.signature)
#Load COSMIC signatures (version 3)
cosmic.signatures <- get_known_signatures(muttype = "snv")
mmr.sig <- cosmic.signatures[,4]
mmr.matrix <- as.matrix(mmr.sig)
rownames(mmr.matrix) <- mutations

#mayo sample names
sample.names <- unique(mayo.samples$sample)

```

```{r}
#convert context column into list
#each element is a sample, each subelement is a point mutation
mutations.list <- vector(mode = "list", length = length(sample.names))
for (i in 1:length(sample.names)){
  temp.sample.df <- mayo.samples %>%
    filter(sample == sample.names[i])
  mutations.list[[i]] = temp.sample.df$context
}
```

```{r}
#run classifier
classification.df <- get_classification_df(mutations.list, c("SBS6", "FFFPE"),
                                           list(mmr.matrix, ffpe.signature))
```



